title: "M1Ch3L!"

theme: minimal

timeout: 60000

metaDataFormat: yaml

baseURL: https://blog.m1ch3l.biz/

languageCode: en-US

enableGitInfo: true

taxonomies:
  category: categories
  tag: tags
  author: author


permalinks:
  post: "/post/:slug"
author:
  name: M1ch3l
  email: m1ch3l@m1ch3l.biz
  logo: /favicon.ico

enableEmoji: true

params:
  #useSummaryIfNoDescription: true
  description: "Hello, I'm M1ch3l."
  copyright: Copyright (c)
  themeColor: custom
  RSSlink: /index.xml
  title: M1ch3l

  organizationName: Ultreme M1ch3l
#  organizationLogo: /img/logo_square-1200x1200.png

  navbarLogo: /favicon.ico

  logoSVG: /favicon.ico
  logoPNG: /favicon.ico
  defaultFeaturedImage: /favicon.ico

  # APP
  appName: M1ch3l
#  appCategory: Messaging
#  appOperatingSystem:
#    - Android
#    - iOS
#    - OSX
#    - Windows

  # SEO
  name: "M1ch3l"
  bio: "Hello, my name is M1ch3l."
  location: "Paris, France"
#  twitter: "m1ch3l"
  github: "ultreme"
#  medium: "m1ch3l"
  #facebook: ""
#  linkedin: m1ch3l
  #googleplus:
  #instagram:
  #slack_url:

  useSummaryIfNoDescription: true

  keepReadingStr: More
  backtotopStr: Up
  shareStr: Share
  pageNotFoundTitle: "404 - Page not found"

  author: M1ch3l
  githubUsername : "ultreme"
  accent : "purple"
  showBorder : true
  backgroundColor : "white"
  font : "Raleway" # should match the name on Google Fonts!
  highlight : true
  highlightStyle : "solarized-dark"
  highlightLanguages : ["go", "haskell", "kotlin", "scala", "swift"]



imaging:
  resampleFilter: linear
  quality: 95
  anchor: smart


#disqusShortname: "username"
googleAnalytics: "A-51632370-5"


menu:
  main:
    - url: /
      name: Home
      weight: 1
    - url: /post/
      name: Posts
      weight: 2

  icon:
    - url: https://ultre.me
      name: "Ultreme"
      weight: 1
# github
# twitter